// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYAaEdhQY_jNmCo8jTQty7cWCIBsRm6Oc',
    appId: '1:926597238864:web:02c3bf5141f46b09c28155',
    messagingSenderId: '926597238864',
    projectId: 'lessontracker-1beeb',
    authDomain: 'lessontracker-1beeb.firebaseapp.com',
    storageBucket: 'lessontracker-1beeb.firebasestorage.app',
    measurementId: 'G-R7WCR2WL9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkQjW8-2kDqVgIz-u0fRREIVJmxkM1Y0',
    appId: '1:926597238864:android:6ae151857b69d6c2c28155',
    messagingSenderId: '926597238864',
    projectId: 'lessontracker-1beeb',
    storageBucket: 'lessontracker-1beeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyglEW9d8aJvlO9gGi4wNT_e8l4mBoriM',
    appId: '1:926597238864:ios:34f92c1d1ae50facc28155',
    messagingSenderId: '926597238864',
    projectId: 'lessontracker-1beeb',
    storageBucket: 'lessontracker-1beeb.firebasestorage.app',
    iosBundleId: 'com.lessontracker.lessonTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyglEW9d8aJvlO9gGi4wNT_e8l4mBoriM',
    appId: '1:926597238864:ios:34f92c1d1ae50facc28155',
    messagingSenderId: '926597238864',
    projectId: 'lessontracker-1beeb',
    storageBucket: 'lessontracker-1beeb.firebasestorage.app',
    iosBundleId: 'com.lessontracker.lessonTracker',
  );
}
